image: docker:19.03.0
services:
  - docker:19.03-dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

cache:
  paths:
    - .m2/repository

stages:
  - test
  - build
  - package

test:
  stage: test
  image: maven:3.6.3-jdk-11
  script: "mvn package -B -V -e -fae -Pprod -DskipTests"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

maven-build:
  stage: build
  image: maven:3.6.3-jdk-11
  script: "mvn package -B -V -e -fae -Pprod -DskipTests"
  retry: 2
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'

docker-build:
  stage: package
  before_script:
    - API_VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
    - docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$API_VERSION -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$API_VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
  dependencies:
    - maven-build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
