image: docker:19.03.0
services:
  - docker:19.03-dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

cache:
  paths:
    - .m2/repository

stages:
  - test
  - build
  - package


test:
  stage: test
  image: maven:3.6.3-jdk-11
  script: "mvn package -B -V -e -fae -Pprod -DskipTests"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

maven-build:
  stage: build
  image: maven:3.6.3-jdk-11
  script: "mvn package -B -V -e -fae -Pprod -DskipTests"
  retry: 2
  cache:
    paths:
      - .m2/repository
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'

docker-build:
  stage: package
  before_script:
    - apk add maven
    - API_VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
    - docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN
    - docker login registry.dev.juniorisep.com -u $ACCESS_TOKEN -p $ACCESS_TOKEN
  script:
    - docker build -t iseplife/api:$API_VERSION -t iseplife/api:latest -t registry.dev.juniorisep.com/iseplife/api .
    - docker push iseplife/api:$API_VERSION
    - docker push iseplife/api:latest
    - docker push registry.dev.juniorisep.com/iseplife/api
  dependencies:
    - maven-build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
