deploy:
  image : ruby:latest
  script:
  - apt-get update -yq
  - apt-get install -yq ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=iseplife-api --api-key=$HEROKU_API_KEY
  only:
  - master
