INSERT IGNORE INTO role (id, role) VALUES (1, "ROLE_ADMIN");
INSERT IGNORE INTO role (id, role) VALUES (2, "ROLE_POST_MANAGER");
INSERT IGNORE INTO role (id, role) VALUES (3, "ROLE_USER_MANAGER");
INSERT IGNORE INTO role (id, role) VALUES (4, "ROLE_CLUB_MANAGER");
INSERT IGNORE INTO role (id, role) VALUES (5, "ROLE_EVENT_MANAGER");
INSERT IGNORE INTO role (id, role) VALUES (6, "ROLE_STUDENT");

INSERT IGNORE INTO club_role (id, name) VALUES (1, "PRESIDENT");
INSERT IGNORE INTO club_role (id, name) VALUES (2, "TREASURER");
INSERT IGNORE INTO club_role (id, name) VALUES (3, "MEMBER");
